### ISSUE TITLE
Not working for 2020.

### ISSUE THREAD

**Issue by czr137** [space-physics/msise00#16]
I can run for certain years and not others

For instance these two work (2016 and 2024)
```
atmos = msise00.run(time=datetime(2016, 3, 31, 12), altkm=np.arange(0, 110.5, .5), glat=10., glon=13.)
atmos = msise00.run(time=datetime(2024, 3, 31, 12), altkm=np.arange(0, 110.5, .5), glat=10., glon=13.)
```
But 2020 gives an error:
```
>>> atmos = msise00.run(time=datetime(2020, 3, 31, 12), altkm=np.arange(0, 110.5, .5), glat=10., glon=13.)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/czr137/miniconda3/envs/ecmwf-osiris/lib/python3.7/site-packages/msise00/base.py", line 56, in run
    atmos = rungtd1d(time, altkm, glat.squeeze()[()], glon.squeeze()[()], indices)
  File "/home/czr137/miniconda3/envs/ecmwf-osiris/lib/python3.7/site-packages/msise00/base.py", line 111, in rungtd1d
    indices = gi.getApF107(time, smoothdays=81).squeeze()
  File "/home/czr137/miniconda3/envs/ecmwf-osiris/lib/python3.7/site-packages/geomagindices/base.py", line 23, in get_indices
    dat = load(fn)
  File "/home/czr137/miniconda3/envs/ecmwf-osiris/lib/python3.7/site-packages/geomagindices/io.py", line 25, in load
    inds.append(readmonthly(fn))
  File "/home/czr137/miniconda3/envs/ecmwf-osiris/lib/python3.7/site-packages/geomagindices/io.py", line 99, in readmonthly
    dat = np.loadtxt(fn, comments=("#", ":"), usecols=(0, 1, 7, 8, 9, 10))
  File "/home/czr137/miniconda3/envs/ecmwf-osiris/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1159, in loadtxt
    for x in read_data(_loadtxt_chunksize):
  File "/home/czr137/miniconda3/envs/ecmwf-osiris/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1080, in read_data
    vals = [vals[j] for j in usecols]
  File "/home/czr137/miniconda3/envs/ecmwf-osiris/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1080, in <listcomp>
    vals = [vals[j] for j in usecols]
IndexError: list index out of range
```

* Linux
* Python versions
  * geomagindices         1.2.7
  * msise00 1.8.0

**Comment by scivision** [comment]
Thanks this is a geomagindices issue. I haven't looked into the cause yet, but I see the same error for this datetime. Thanks!

**Comment by czr137** [comment]
@scivision will you follow up with geomagindices, or would you like me to? It may have greater import if you do it.
